services:
  postgres:
    container_name: bookwise-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bookwise
      PGDATA: /data/postgres
    volumes:
      - ./src/lib/prisma/data/pg:/data/postgres